stackblitz-labs/pkg.pr.new

packages/cli/index.ts

Remove the backticks that surround the command `npm i ...` in output messages.
The reason is that when the message is printed as the output of a step in the workflow, the trailing backtick will be regarded as a part of the clickable link. So when a user clicks it, the browser will open a wrong link (with the trailing backtick encoded to `%60` and appended to that link) and reports a 404 error.
[![image](https://github.com/stackblitz-labs/pkg.pr.new/assets/10386119/67cfcfc9-bb99-4a54-8934-23b07f7c9b2d)](https://github.com/biomejs/biome/actions/runs/9206513359/job/25360381248#step:8:17)

chore: update output message

---

README.md
e2e/publish.test.mts
packages/backend/server/routes/webhook.post.ts
packages/cli/environments.ts
packages/cli/index.ts

The issue happens here https://github.com/QwikDev/qwik/pull/6389
when other workflows finish, the workflow key would be removed since they all share the same workflow key. And when it is removed, the publish step would crash since there is not workflow key for that step.
what I'm trying to do here is to make the workflow key unique to each step.

fix: conflict on run id

---

packages/backend/package.json
packages/cli/package.json
packages/utils/package.json
pnpm-lock.yaml

1. With the `--compact` flag on, we use [`query-registry`](https://github.com/velut/query-registry) to query the manifest file `package.json`.
2. It uses [`zod-package-json`](https://github.com/velut/zod-package-json) to validate the fields.
3. One of the field `sideEffects` was only allowed to have `boolean` values, while [an array of patterns are also allowed in `webpack`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free), thus causing packages setting this field to an array to fail the validation from `query-registry`, which will make `--compact` fail.
4. This was recently [fixed in `zod-package-json`](https://github.com/velut/zod-package-json/commit/6a197db4004f54113841b9bff466213dc162f17d), and the fix [is shipped in the latest version of …

fix: bump `query-registry`

---

packages/backend/server/routes/webhook.post.ts
packages/backend/server/types.ts
packages/backend/server/utils/markdown.ts

Now vite main branch points to https://github.com/vitejs/vite/pull/17438 because of the pr key collision.

fix: proper key for pull request event

---

README.md
package.json
packages/cli/index.ts
packages/cli/template.ts

As I learnt while debugging #136, different shell environments will parse glob patterns differently (https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784)
This PR updates the docs to pass all packages/templates as strings, to help other users avoid the unexpected behaviour I encountered.
It also removes the `fg.isDynamicPattern` check, since passing a non-dynamic path to `fg.sync` doesn't alter the path. This is solely a readability change and I'm happy to undo it if you want!

fix: Safely pass glob pattern args as strings

---

packages/cli/package.json

The instructions say to run `pnpx pkg-pr-new` but when you check that out on https://npmjs.com/package/pkg-pr-new you see v little reassuring information pointing back here. So if reading a GitHub Action which uses this, it's hard to find where it comes from.
This adds `repository` to the CLI package. I haven't looked at the other packages but probably they could get the same treatment. Happy to add them to this PR if maintainers would want that.

set `repository` field in cli package.json

---

packages/utils/index.ts
packages/utils/package.json
pnpm-lock.yaml

The current regex doesn't handle github shorthands `user/repo` or `github:user/repo` properly. This PR fixes that.

fix: use hosted-git-info instead of manually parsing repository field

---

packages/utils/index.ts
packages/utils/package.json
pnpm-lock.yaml

Reverts stackblitz-labs/pkg.pr.new#149
closes #150
turns out it isn't needed because npm normalizes the repository url while publishing, so registry has `git+https://github.com/vuejs/vitepress.git` even when we have `github:vuejs/vitepress` in our package.json.

revert: "use hosted-git-info instead of manually parsing repository field"

---

packages/backend/server/routes/publish.post.ts

Since https://github.com/vitejs/vite/pull/16471 has so many comments, github pagination only receives the first 30! 
This PR tries to use proper pagination. The reason we need to see comments is to find which one is ours, so we avoid commenting again.

fix: paginate comments 

---

packages/backend/server/utils/markdown.ts

When using bun, the command would be undefined
This PR fixes that

feat: support bun in the PR comments

---

packages/backend/server/utils/markdown.ts

example - https://github.com/vuejs/vitepress/pull/4100#issuecomment-2270690009
there is also an extra bullet at end in that comment, but I guess it's because #166 isn't released yet?

fix: undefined is rendered as link if --no-template is passed

---

README.md
packages/backend/server/routes/publish.post.ts
packages/backend/server/utils/markdown.ts
packages/cli/index.ts

For instance, check this PR  in TanStack, https://github.com/TanStack/query/pull/7861
The problem is when repository has too many packages the amount of scroll on the PR page will increase, adding another detail to the pkg.pr.new links conditional with a flag like `--collapsed-links` will help resolve this case

feat: add `--only-templates` flag

---

README.md

Capawesome recently started using pkg.pr.new to continuously publish more than 30 packages. Thanks for this great project!
The idea to list Capawesome came from [Mohammad](https://x.com/aslemammadam/status/1825538789525397809?t=k9Xz6D9ZXLbWibNDwFk3nQ)! 🙌

docs: list Capawesome as project using pkg.pr.new

---

package.json
packages/cli/index.ts
pnpm-lock.yaml

feat: output json

---

README.md

Vite PWA only, I'm using this package in all repos.
**NOTE**: this PR using picture inside the link to support prefer-color-scheme.

chore: add `VitePWA` organization to projects using

---

packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

pkg.pr.new looks really interesting and promising, but its dependency count is not optimal. this PR drops 25 dependencies by replacing `detect-package-manager` with [`package-manager-detector`](https://www.npmjs.com/package/package-manager-detector) and `fast-glob` with [`tinyglobby`](https://www.npmjs.com/package/tinyglobby)
there are more places to improve the dependency count that i didn't try to replace due to me not having enough experience replacing, like replacing `pkg-types` with something lighter, `@jsdevtools/ez-spawn` with `tinyexec` and it looks like `query-registry` too with normal `fetch()` calls. either way, thanks for pkg.pr.new!
```
Package size report
===================
Package info for "pkg-pr-new@0.0.20": 39 MB
Released: 2024-08-06 18:40:40.604 +0000 UTC (2w ago) …
```

refactor: use 25 less dependencies

---

README.md

Besides an a11y issue (ie. "here" as link text), this link is basically the main CTA on this page so might as well stand out a bit.

Update main link text README.md

---

README.md

Continuation of https://github.com/stackblitz-labs/pkg.pr.new/pull/190
Adds the inverted logo variant for `intlify` to support both dark and light preferences.
Thanks to @userquin for the heads up and example 😄 https://github.com/stackblitz-labs/pkg.pr.new/pull/192

chore: support dark and light theme `intlify` logo

---

README.md

I've just integrated it in `nuqs`, where I already had a manual snapshot release workflow, but which "polluted" the NPM registry. This is miles better for preview versions.
Workflow: https://github.com/47ng/nuqs/blob/next/.github/workflows/pkg.pr.new.yml

doc: Add 47ng to list of users

---

README.md

We use pkg-pr-new to try out PR preview releases https://github.com/nuxt-modules/i18n/pull/3075, thank you!

chore: add `nuxt-modules/i18n` logo

---

.whitelist

Currently tried removing the .map files from mermaid to fit under the size limit. 
But that didn't work https://github.com/mermaid-js/mermaid/actions/runs/10906565961/job/30268106980?pr=5825

Add mermaid-js/mermaid to .whitelist

---

packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

tinyglobby 0.2.7 is out which removes the need for that workaround

refactor: remove `.` pattern workaround

---

README.md
packages/backend/server/routes/multipart/create.post.ts
packages/backend/server/routes/publish.post.ts
packages/cli/index.ts

Very minor, but GitHub is spelled with a capital H ;)

fix: correct casing for GitHub

---

README.md

We're using pkg.pr.new in our playground when you add `?version=pr-xxxxx` to the URL. Super helpful for previewing upcoming features!

Add Svelte to list of users

---

packages/cli/index.ts

Resolves https://github.com/bluwy/publint/issues/114
this by default includes a publint url which also changes the structure of logs in pkg.pr.new! this is way cleaner now.

feat: publint

---

README.md

Adds https://tutorialkit.dev/ to list of users.

chore: add `tutorialkit` to list of users

---

.github/workflows/ci.yml
README.md
packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

feat: --packageManager=XYZ

---

.whitelist

Greetings!
I'm from the @withstudiocms team, and we were hoping to be able to use `pkg.pr.new` for StudioCMS snapshots!
StudioCMS is a CMS that is built into an Astro Integration.
Currently getting the [following error](https://github.com/withstudiocms/studiocms/actions/runs/12010328848/job/33476935706?pr=385) and was directed to open a PR here to resolve!
Hopefully we can get access to the whitelist :smiley: as our CMS is broken out into multiple packages that seem to be causing a size issue :sweat_smile:

Add studiocms to whitelist

---

packages/cli/index.ts

fix: ensure template glob doesn't evaluate to `false`

---

.github/workflows/stats.yml
packages/backend/server/routes/publish.post.ts
packages/backend/server/routes/webhook.post.ts

the hash function of ohash has a short length and hitting hash collisions was kinda inevitable! 
so let's use proper keys from now on, for PRs, since they're long living, compared to workflow_run keys.
this would hopefully fix the element-plus issue we have.

fix: avoid pr hash collisions

---

.editorconfig
.github/workflows/stats.yml
.github/workflows/test.yml
.prettierignore
packages/backend/script/update-webhook-url.ts
packages/backend/server/routes/[owner]/[repo]/[packageAndRefOrSha].get.ts
packages/backend/server/routes/multipart/create.post.ts
packages/backend/server/routes/publish.post.ts
packages/backend/server/routes/stats.get.ts
packages/backend/server/routes/webhook.post.ts
packages/backend/server/types.ts
packages/backend/server/utils/bucket.ts
packages/backend/server/utils/markdown.ts
packages/backend/server/utils/octokit.ts
packages/cli/index.ts
packages/utils/index.ts
templates/example-1/index.js

Runs the formatter and adds `.editorconfig` / `.prettierignore`.

chore: run format

---

package.json
packages/utils/index.test.ts
packages/utils/index.ts
pnpm-lock.yaml
vitest.config.js

This adds vitest to the monorepo and uses workspaces to run it from there.
It also adds an initial set of simple tests to the utils package.

test: add vitest and initial utils tests

---

package.json
pnpm-lock.yaml

- Updates Vitest to latest version with security patch for critical vulnerability: https://github.com/vitest-dev/vitest/releases/tag/v3.0.5

chore(dev-deps): security patch to vitest

---

.github/workflows/ci.yml
.github/workflows/lint-check.yml
.github/workflows/test.yml

https://github.com/nodejs/corepack/issues/612

fix: ci fails caused by corepack signature check

---

package.json
packages/backend/package.json
pnpm-lock.yaml

We confirmed the simulator from the preview pkg 💪 . We released the stable version with the same, simply bumping over to it.

chore: stable @simulacrum/github-api-simulator@0.5.4

---

packages/backend/e2e.test.ts
packages/backend/script/generate-dev-vars.ts
packages/backend/server/routes/check.post.ts
packages/backend/server/routes/publish.post.ts

It appears that calls to the simulated GitHub endpoint were failing. However, the `octokit` instance was failing at creation due to an issue with the private key that was generated for testing purposes. Despite as such, the tests were still passing.
- Adjusted the private key to output as single line string. `octokit` could then make a valid instance.
- Removed the code paths which used `test` as dependency as they were not required.
- Added a few new org/repo combinations that would be used now that calls were being made to the GitHub simulator.

fix: generate valid dev private key

---

README.md
packages/backend/server/routes/publish.post.ts
packages/backend/server/utils/markdown.ts
packages/cli/index.ts

Fixes #263 
Adds a `--bin` flag to allow for displaying an execute command instead of an install command i.e. instead of `npm i` it would be `npx`
Forgive me I am not exactly sure how to test my changes so let me know what I can do!

feat: allow for showing `npx` instead of `npm install`

---

packages/cli/index.ts

fix: --compact with --json depUrl

---

.whitelist

Hi there, thank you for making a fantastic tool!
[ReScript](https://github.com/rescript-lang/rescript) team is trying pkg.pr.new from https://github.com/rescript-lang/rescript/pull/7412 and is facing the 20 MB limit.
Our npm packages are ~70 MiB, including `rescript` and per-platform binary packages.

chore: add ReScript to the `.whitelist`

---

packages/app/server/utils/markdown.ts

https://github.com/yarnpkg/berry/blob/666aa3ac20de796e0159f9d4aa029715ccf5ec55/packages/plugin-essentials/sources/commands/add.ts#L184
Yarn now requires package names to be explicitly specified in descriptor when using `add` command.

fix: specify package name in descriptor for yarn

---

packages/cli/index.ts

`--yarn` was not parsed correctly, causing the following `'./packages/*'` to be ignored.
Ref: https://github.com/stackblitz-labs/pkg.pr.new/issues/321

fix: Correctly parse `--yarn`

---

README.md
packages/cli/environments.ts
packages/cli/index.ts

Added some useful context.
- `*.outputs.sha`: determined package tag (the short sha)
- `*.outputs.urls`: space-separated package URLs, can be passed `npm i` or `pnpm add` directly.
- `*.outputs.packages`: space-separated package locators, can be passed `yarn add` directly.
Resolves #363

feat(cli): append some context to `GITHUB_OUTPUT`
