stackblitz-labs/pkg.pr.new

packages/backend/wrangler.toml

This value should be specified by environment variables

Remove CF account ID from wrangler.toml

---

packages/backend/server/routes/[owner]/[repo]/index.get.ts
packages/backend/server/utils/markdown.ts

thanks to @patak-dev for the idea

chore: shorter urls

---

README.md
e2e/publish.test.mts
package.json
packages/backend/package.json
packages/backend/server/routes/[packageAndRefOrSha].get.ts
packages/backend/server/routes/publish.post.ts
packages/backend/server/utils/markdown.ts
packages/cli/index.ts
packages/cli/package.json
packages/utils/index.ts
packages/utils/package.json
pnpm-lock.yaml

feat: --compact

---

.github/workflows/remove-stale.yml
e2e/fixtures/pr.pull_request.json
packages/backend/nitro.config.ts
packages/backend/script/update-webhook-url.ts
packages/backend/server/routes/[owner]/[repo]/[packageAndRefOrSha].get.ts
packages/backend/server/routes/[owner]/[repo]/index.get.ts
packages/backend/server/routes/[packageAndRefOrSha].get.ts
packages/backend/server/routes/publish.post.ts
packages/backend/server/routes/rm/stale.post.ts
packages/backend/server/routes/webhook.post.ts
packages/backend/server/types.ts
packages/backend/server/utils/bucket.ts
packages/backend/server/utils/commit.ts
packages/backend/server/utils/markdown.ts
packages/utils/index.ts

Resolves #27 
- workflow dispatch rm-stale
- fix few bugs with pull request messages
- remove check runs bucket and use github api 
- remove pull request comments bucket & use github api

chore: manual removals 3 

---

packages/backend/server/routes/webhook.post.ts

fix: synchronize pr event

---

e2e/publish.test.mts
package.json
packages/backend/server/routes/[owner]/[repo]/index.get.ts
patches/radix3@1.1.2.patch
pnpm-lock.yaml

https://github.com/radix-vue/radix-vue/pull/933
https://github.com/pmndrs/valtio/pull/898

fix: short mode route unmatched

---

packages/backend/server/utils/markdown.ts

A tiny PR to close #64 :)
And thanks for this useful tool ❤️

fix: remove extra spaces in markdown

---

packages/backend/server/routes/publish.post.ts

feat: whitelist

---

packages/backend/server/utils/markdown.ts

feat: pr new badge

---

packages/backend/server/routes/check.post.ts
packages/backend/server/routes/publish.post.ts
packages/backend/server/routes/template/[uuid].get.ts
packages/backend/server/utils/markdown.ts
packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

feat: template package indentation

---

packages/cli/index.ts
packages/utils/index.ts

Addresses https://github.com/stackblitz-labs/pkg.pr.new/issues/104#issuecomment-2160112443
I'm not good at writing messages. Feel free to reword~

chore: add detailed error messages for `--compat` flag verification

---

README.md
package.json
packages/backend/server/routes/publish.post.ts
packages/backend/server/utils/markdown.ts
packages/cli/index.ts
packages/utils/index.ts

feat: comment mode (`--comment`)

---

.github/workflows/ci.yml
packages/cli/index.ts

Resolves https://github.com/nuxt-hub/core/pull/187

fix: revert package json after edit

---

.github/workflows/ci.yml
packages/cli/index.ts

fix: passing multiple lines 

---

packages/cli/index.ts
playgrounds/playground-b/package.json

fix: skip private packages

---

packages/cli/index.ts

fix: Allow `"private": true` in templates

---

packages/cli/environments.ts
packages/cli/index.ts

maybe fix: #141, I'm not sure 😂

fix: always ignore node_modules and .git

---

README.md
packages/cli/index.ts

feat: inform when publishing the same twice

---

.whitelist

This project needs around `25Mb` of space.

Update .whitelist with o1js repository.

---

packages/cli/index.ts

Resolves https://github.com/mui/material-ui/pull/42984#issuecomment-2241818041

feat: --peerDeps

---

packages/backend/package.json
packages/backend/script/update-webhook-url.ts
pnpm-lock.yaml

I dont know if the call is equivalent.  there are no tests... and well. needs manual testing.

chore: replace jsonwebtoken with fast-jwt

---

packages/backend/server/utils/markdown.ts
packages/cli/index.ts

fix: hanging process

---

README.md

Companies and projects using pkg.pr.new have a special characteristic, they are "legendary"!

feat: companies

---

README.md

chore: adding TresJS to projects using pkg.pr.new

---

README.md

Related https://github.com/unocss/unocss/pull/4083
Thanks `pkg.pr.new`

chore: add `unocss` to projects using

---

README.md

related https://github.com/intlify/vue-i18n/pull/1924
Thank you!

chore: add `intlify` project to projects using

---

README.md

We just recently added this to [NuxtAuth](https://github.com/sidebase/nuxt-auth) and are loving it! Amazing work and great idea (I would have never thought of this, but it solves so many pain points 😊)

chore: add sidebase to projects using `pkg.pr.new`

---

packages/backend/server/utils/markdown.ts

x-ref: https://github.com/stackblitz-labs/pkg.pr.new/pull/167#issuecomment-2305224001

fix: undefined is rendered as link if `--no-template` is passed

---

packages/backend/server/routes/[owner]/[repo]/[packageAndRefOrSha].get.ts
packages/backend/server/utils/markdown.ts

Resolves #168 
@slorber this might help you with the yarn issue!

fix: yarn support

---

packages/cli/index.ts

fix: optional deps

---

README.md

Thank you for the awesome project. Rolldown is being developed rapidly and adopting pkg.pr.new accelerates our development velocity by another 10x. Thank you ❤️ .
Rolldown PR: https://github.com/rolldown/rolldown/pull/2090

chore: add Rolldown to README.md

---

package.json
packages/cli/index.ts

fix: no args issue

---

README.md

chore: add element-plus to README.md

---

packages/cli/index.ts

fixing this in tinyglobby will require some work inside a library it uses (fdir), meanwhile this PR fixes it with a workaround, and also optimizes those glob calls by not using `.flatMap`, as tinyglobby supports an array of patterns
ref: #212

fix: correctly handle `.` as a pattern

---

README.md

Reverts stackblitz-labs/pkg.pr.new#219

Revert "doc: Add 47ng to list of users"

---

README.md

Supersedes https://github.com/stackblitz-labs/pkg.pr.new/pull/219

doc: Add nuqs to list of users

---

.whitelist

Related to https://github.com/web-infra-dev/rspack/pull/7757

chore: add rspack to whitelist

---

README.md

@Aslemammad you told me it could be a small but powerful project so here it is 🎉

chore: add `vue-mess-detector` logo to README

---

packages/backend/server/routes/check.post.ts

fix: app is not installed on organization

---

README.md

Support continuous release in wxt repo 🎉
https://github.com/wxt-dev/wxt/pull/955
-----
<a href="https://stackblitz.com/~/github.com/kongmoumou/pkg.pr.new/tree/kongmoumou/patch-60494"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/kongmoumou/pkg.pr.new/tree/kongmoumou/patch-60494)._

chore: add `wxt` logo to README

---

LICENSE
package.json
packages/backend/package.json
packages/cli/package.json

chore: LICENSE

---

.github/workflows/ci.yml
packages/cli/index.ts

fix: File is not defined

---

README.md
packages/backend/server/routes/publish.post.ts

fix: guard undefined workflow

---

.github/workflows/ci.yml
packages/cli/index.ts

fix https://github.com/atinux/nuxt-auth-utils/actions/runs/11042773523/job/30675763904

fix: clean up files

---

README.md

Thanks for your great work! 💗
Rspack PR: https://github.com/web-infra-dev/rspack/pull/7757

chore: add `Rspack` to `README.md`

---

packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

fix: memory leak

---

packages/cli/index.ts
packages/cli/package.json
pnpm-lock.yaml

without infinite loops now 😅 includes changes from #254

chore: update `tinyglobby`

---

README.md

pkg.pr.new really helps a lot in the development of reactive-vscode - It's the only perfect way to check whether the package works well before publishing it. Thank you a lot for the great work!

doc: Add reactive-vscode to list of users

---

README.md

docs: add permissions check to approval-based publish

---

README.md

I just switched fast-check from codesandbox to pkg.pr.new to have previews of my packages for each PR. So far it works really well!
More about fast-check at https://fast-check.dev/.

doc: Add fast-check to list of users

---

README.md

Hey 👋 
Just installed the GitHub application and added `pkg.pr.new` usage in https://github.com/kysely-org/kysely/pull/1219.
🍻

chore: add `kysely` to projects that use `pkg.pr.new`.

---

README.md

chore: add `vitest` to list of users

---

packages/backend/server/routes/webhook.post.ts

Resolves #289 
We used to remove the cursor (`@23` or `@chore/23`) after the ref was being deleted (closed/merged). 
Let's not do it anymore since it creates unexpected behavior since we already have the strict 6 months deadline.

chore: do not remove cursors after ref deletion

---

packages/cli/index.ts

`readPackageJSON` is generally used to traverse the filesystem for the closest `package.json`, then attempt to parse it via `JSON.parse`.
In all cases, we pass an absolute path to a `package.json`, which means we don't actually make use of what this function does (other than `JSON.parse` at the very end).
This refactors such that we simply `JSON.parse` ourselves and use the `PackageJson` type from `pkg-types`.
We also currently re-read the `package.json` when we want to `writeDeps`. This is so we can revert our changes if needed. Since we already read the file earlier in the stack, we now pass that down directly.
---
i've never contributed to this repo, so let me know if any of this is a bad idea and i'll happily close

refactor(cli): resolve `package.json` files directly

---

packages/backend/server/routes/publish.post.ts

chore: check permissions for issues

---

.whitelist

Add Biome to whitelist, I hope the addition is correct.
Here's the action log that led me to this PR: https://github.com/biomejs/biome/actions/runs/13287129475/job/37099926452#step:8:17

chore: add biome to whitelist

---

README.md

chore: update element-plus logo clarity

---

README.md
packages/backend/server/routes/publish.post.ts
packages/cli/index.ts

So I am not sure how to add tests cause I don't think there is a way to intercept the request. But this should fix the issue. So sorry this took so long.

fix: Correct typo in `--bin` flag

---

.whitelist

Hi, thank you for creating pkg.pr.new! We'd love to use it for packaged in the [sanity-io/sanity](https://github.com/sanity-io/sanity) monorepo.
Got [this error](https://github.com/sanity-io/sanity/actions/runs/14190161354/job/39752825172#step:7:19) when setting it up the workflow, which lead me to open this PR.

chore: add sanity to whitelist

---

README.md

Shoutout to the team for building this awesome tool!
Your work has made a big difference.
Thanks a bunch!
useful: https://github.com/ant-design/ant-design/pull/49647

chore: add Ant Design team logo

---

README.md

Hey,
First of all, thanks for creating this amazing project!
We've added pkg.pr.new to TypeORM in [this PR](https://github.com/typeorm/typeorm/pull/11434).

docs(README): add TypeORM to list of projects

---

README.md

(and thanks, team, for the great library ❤️)

chore: add Preply to the companies using pkg.new

---

README.md

Thank You Guys for this Amazing Time Saving Project ❤️

chore: change `radix-vue` link to `reka-ui`

---

README.md

Adds the @playcanvas/react badge to the pk.pr.new README.md 🔥

Adds @playcanvas/react badge
